// <auto-generated />
using System;
using EducaRank.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EducaRank.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104014134_MoreMigration")]
    partial class MoreMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EducaRank.Domain.Models.Aluno", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Etec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NrAvaliacoes")
                        .HasColumnType("integer");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("integer");

                    b.Property<int>("Rm")
                        .HasColumnType("integer");

                    b.Property<int>("SalaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SalaId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("EducaRank.Domain.Models.AlunoCredencial", b =>
                {
                    b.Property<string>("AlunoId")
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AlunoId");

                    b.ToTable("AlunosCredenciais");
                });

            modelBuilder.Entity("EducaRank.Domain.Models.Avaliacao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AlunoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PontuacaoAlterada")
                        .HasColumnType("integer");

                    b.Property<string>("ProfessorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("EducaRank.Domain.Models.Professor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AvaliacoesFeitas")
                        .HasColumnType("integer");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rm")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("EducaRank.Domain.Models.ProfessorCredencial", b =>
                {
                    b.Property<string>("ProfessorId")
                        .HasColumnType("text");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProfessorId");

                    b.ToTable("ProfessoresCredenciais");
                });

            modelBuilder.Entity("EducaRank.Domain.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeSala")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProfessorId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("EducaRank.Domain.Models.Aluno", b =>
                {
                    b.HasOne("EducaRank.Domain.Models.Sala", "Sala")
                        .WithMany("Alunos")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("EducaRank.Domain.Models.AlunoCredencial", b =>
                {
                    b.HasOne("EducaRank.Domain.Models.Aluno", null)
                        .WithOne("Credencial")
                        .HasForeignKey("EducaRank.Domain.Models.AlunoCredencial", "AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EducaRank.Domain.Models.Avaliacao", b =>
                {
                    b.HasOne("EducaRank.Domain.Models.Aluno", "Aluno")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EducaRank.Domain.Models.Professor", "Professor")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("EducaRank.Domain.Models.ProfessorCredencial", b =>
                {
                    b.HasOne("EducaRank.Domain.Models.Professor", null)
                        .WithOne("Credencial")
                        .HasForeignKey("EducaRank.Domain.Models.ProfessorCredencial", "ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EducaRank.Domain.Models.Sala", b =>
                {
                    b.HasOne("EducaRank.Domain.Models.Professor", null)
                        .WithMany("Salas")
                        .HasForeignKey("ProfessorId");
                });

            modelBuilder.Entity("EducaRank.Domain.Models.Aluno", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Credencial");
                });

            modelBuilder.Entity("EducaRank.Domain.Models.Professor", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Credencial");

                    b.Navigation("Salas");
                });

            modelBuilder.Entity("EducaRank.Domain.Models.Sala", b =>
                {
                    b.Navigation("Alunos");
                });
#pragma warning restore 612, 618
        }
    }
}
